//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationApp.Data.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class locationAppEntities : DbContext
    {
        public locationAppEntities()
            : base("name=locationAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<block> blocks { get; set; }
        public virtual DbSet<build> builds { get; set; }
        public virtual DbSet<campu> campus { get; set; }
        public virtual DbSet<campussite> campussites { get; set; }
        public virtual DbSet<department> departments { get; set; }
        public virtual DbSet<departmentroom> departmentrooms { get; set; }
        public virtual DbSet<floor> floors { get; set; }
        public virtual DbSet<mainunit> mainunits { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<roomtype> roomtypes { get; set; }
        public virtual DbSet<site> sites { get; set; }
        public virtual DbSet<subunit> subunits { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<usercontact> usercontacts { get; set; }
        public virtual DbSet<usercontacttype> usercontacttypes { get; set; }
        public virtual DbSet<userdepartment> userdepartments { get; set; }
        public virtual DbSet<userlogin> userlogins { get; set; }
        public virtual DbSet<userpassword> userpasswords { get; set; }
        public virtual DbSet<userrole> userroles { get; set; }
        public virtual DbSet<usertitle> usertitles { get; set; }
        public virtual DbSet<useruserrole> useruserroles { get; set; }
    }
}
